'use strict';
const KEY='kabuto_insects', EXTRA='kabuto_v1_business', LANG='kabuto_v1_lang';
const $=id=>document.getElementById(id), E=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n};
const dict={zh:{home:'总览',insects:'昆虫档案',breeding:'繁育管理',pedigree:'血统中心',sales:'经营管理',tools:'智能工具',settings:'设置与备份',local:'本地体验版',backup:'导出备份',welcome:'繁育工作台',welcomeDesc:'从个体档案到血统、繁育与经营，集中管理。',add:'新增',empty:'暂无记录',save:'保存',cancel:'取消',delete:'删除',edit:'编辑',view:'查看',certificate:'生成证书'},ja:{home:'概要',insects:'個体管理',breeding:'繁殖管理',pedigree:'血統',sales:'販売管理',tools:'ツール',settings:'設定とバックアップ',local:'ローカル体験版',backup:'バックアップ',welcome:'ブリーダーワークスペース',welcomeDesc:'個体、血統、繁殖、販売を一元管理。',add:'追加',empty:'記録がありません',save:'保存',cancel:'キャンセル',delete:'削除',edit:'編集',view:'表示',certificate:'証明書'},en:{home:'Overview',insects:'Insects',breeding:'Breeding',pedigree:'Pedigree',sales:'Sales',tools:'Tools',settings:'Settings & backup',local:'Local preview',backup:'Export backup',welcome:'Breeder workspace',welcomeDesc:'Manage individuals, lineage, breeding and sales in one place.',add:'Add',empty:'No records yet',save:'Save',cancel:'Cancel',delete:'Delete',edit:'Edit',view:'View',certificate:'Certificate'}};
let lang=localStorage.getItem(LANG)||'zh',page='home',insects=[],extra={breedings:[],sales:[]},selected=null;
const t=k=>(dict[lang]||dict.zh)[k]||k;
const norm=x=>({id:String(x.id||crypto.randomUUID?.()||Date.now()),code:String(x.code||x.name||''),species:String(x.species||''),sex:String(x.sex||'未知'),stage:String(x.stage||'未知'),length:String(x.length||''),weight:String(x.weight||''),hatchDate:String(x.hatchDate||''),emergeDate:String(x.emergeDate||''),father:String(x.father||''),mother:String(x.mother||''),breeding:String(x.breeding||'未配对'),notes:String(x.notes||''),photo:typeof x.photo==='string'&&x.photo.startsWith('data:image/')?x.photo:'',events:Array.isArray(x.events)?x.events.map(e=>({id:String(e.id||uid()),type:String(e.type||''),date:String(e.date||''),note:String(e.note||'')})):[]});
function uid(){return globalThis.crypto?.randomUUID?.()||String(Date.now())+Math.random().toString(36).slice(2)}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');insects=Array.isArray(raw)?raw.map(norm):[]}catch{alert('昆虫数据读取失败，请先保留原始备份');insects=[]}try{const x=JSON.parse(localStorage.getItem(EXTRA)||'{}');extra={breedings:Array.isArray(x.breedings)?x.breedings:[],sales:Array.isArray(x.sales)?x.sales:[]}}catch{extra={breedings:[],sales:[]}}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(insects));localStorage.setItem(EXTRA,JSON.stringify(extra));return true}catch{alert('保存失败，可能是照片过大或浏览器存储已满。请导出备份。');return false}}
function mount(parent,...nodes){nodes.forEach(n=>parent.append(n));return parent}
function b(label,fn,cls='secondary small'){const x=E('button',label);x.className=cls;x.type='button';x.onclick=fn;return x}
function box(title){const d=E('section','','card');if(title)d.append(E('h2',title));return d}
function row(label,value){const d=E('div');d.append(E('small',label),E('strong',String(value||'—')));return d}
function field(label,key,value='',kind='text',opts){const d=E('div','','field');const l=E('label',label);let inp;if(opts){inp=E('select');opts.forEach(o=>{const op=E('option',o);op.value=o;inp.append(op)})}else if(kind==='textarea'){inp=E('textarea')}else{inp=E('input');inp.type=kind}inp.name=key;inp.value=value??'';if(key==='code')inp.required=true;d.append(l,inp);return d}
function formDialog(title,fields,onSave){const f=E('form');const grid=E('div','','formgrid');fields.forEach(a=>grid.append(field(...a)));f.append(grid);const actions=E('div','','actions');actions.append(b(t('save'),()=>{},'hide'));const submit=E('button',t('save'));submit.type='submit';actions.append(submit,b(t('cancel'),close));f.append(actions);f.onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(f));onSave(values,f)};open(title,f);return f}
function open(title,content){$('modalTitle').textContent=title;$('modalBody').replaceChildren(content);$('modal').classList.remove('hide')}
function close(){$('modal').classList.add('hide')}
function title(h,desc){$('pageTitle').textContent=h;$('pageDesc').textContent=desc}
function navigate(p){page=p;close();render()}
function render(){const nav=$('nav');nav.replaceChildren();[['home','◈'],['insects','🪲'],['breeding','♡'],['pedigree','♧'],['sales','▣'],['tools','✦'],['settings','⚙']].forEach(([key,icon])=>{const x=b(icon+'  '+t(key),()=>navigate(key));x.className=page===key?'active':'';nav.append(x)});$('lang').value=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));const c=$('content');c.replaceChildren();({home:homePage,insects:insectsPage,breeding:breedingPage,pedigree:pedigreePage,sales:salesPage,tools:toolsPage,settings:settingsPage}[page]||homePage)(c);c.append(E('div','Kabuto-Lub V1.0 · Local-first preview · No cloud sync / live AI / payments','','footer'))}
function homePage(c){title(t('welcome'),t('welcomeDesc'));const s=E('div','','stats');[['个体总数',insects.length],['成虫',insects.filter(x=>x.stage==='成虫').length],['繁育批次',extra.breedings.length],['销售记录',extra.sales.length]].forEach(([k,v])=>{const d=E('div','','stat');d.append(E('small',k),E('b',v));s.append(d)});c.append(s);const g=E('div','','grid');[['🪲 我的昆虫','记录个体资料、照片与成长事件',()=>navigate('insects')],['🧬 血统关系','查看父母、子代与电子记录证书',()=>navigate('pedigree')],['📊 经营记录','跟踪繁育批次、销售和成本',()=>navigate('sales')]].forEach(([h,p,fn])=>{const d=box(h);d.append(E('p',p),b('打开 →',fn));g.append(d)});c.append(g);const note=E('div','当前为可运行的本地体验版：数据只保存在此浏览器。正式商用前仍需部署安全的账号、云数据库、服务端 AI 与支付系统。','','notice');note.className='notice';c.append(note)}
function insectsPage(c){title(t('insects'),'昆虫个体、成长阶段、照片与事件记录');const tb=E('div','','toolbar');const h=E('h2','个体列表');const ac=E('div','','actions');const search=E('input');search.className='search';search.placeholder='搜索编号 / 品种';search.oninput=()=>list();ac.append(search,b('＋ '+t('add'),()=>insectEditor()));tb.append(h,ac);c.append(tb);const holder=E('div');c.append(holder);function list(){holder.replaceChildren();const data=insects.filter(x=>(x.code+' '+x.species).toLowerCase().includes(search.value.toLowerCase()));if(!data.length){holder.append(E('div',t('empty'),'empty'));return}const table=makeTable(['编号','品种','性别','阶段','操作'],data.map(x=>[x.code,x.species,x.sex,x.stage,[b(t('view'),()=>detail(x.id)),b(t('edit'),()=>insectEditor(x.id))]]));holder.append(table)}list()}
function makeTable(headers,rows){const w=E('div','','tablewrap'),table=E('table','','table'),thead=E('thead'),tr=E('tr');headers.forEach(h=>tr.append(E('th',h)));thead.append(tr);const tbody=E('tbody');rows.forEach(cells=>{const r=E('tr');cells.forEach(cell=>{const td=E('td');if(Array.isArray(cell))cell.forEach(n=>td.append(n));else if(cell instanceof Node)td.append(cell);else td.textContent=String(cell??'—');r.append(td)});tbody.append(r)});table.append(thead,tbody);w.append(table);return w}
const insectFields=x=>[['昆虫编号 *','code',x.code],['品种','species',x.species],['性别','sex',x.sex,'text',['公','母','未知']],['成长阶段','stage',x.stage,'text',['卵','L1','L2','L3','蛹','成虫','未知']],['体长 (mm)','length',x.length,'number'],['体重 (g)','weight',x.weight,'number'],['孵化日期','hatchDate',x.hatchDate,'date'],['羽化日期','emergeDate',x.emergeDate,'date'],['父虫编号','father',x.father],['母虫编号','mother',x.mother],['繁育状态','breeding',x.breeding],['备注','notes',x.notes,'textarea']];
function insectEditor(id){const old=insects.find(x=>x.id===id),x=old||norm({});const f=formDialog(old?'编辑昆虫':'新增昆虫',insectFields(x),async(v,form)=>{v.code=v.code.trim();if(!v.code)return alert('请输入编号');if(insects.some(y=>y.code===v.code&&y.id!==id))return alert('编号已存在');if(v.father===v.code||v.mother===v.code)return alert('不能将自己设为父母');const file=form.querySelector('[name="photo"]')?.files[0];let photo=x.photo;if(file){if(!file.type.startsWith('image/'))return alert('请选择图片');photo=await shrink(file)}const item=norm({...x,...v,photo});if(old){const idx=insects.findIndex(z=>z.id===id);insects[idx]=item}else insects.push(item);if(persist()){close();render()}});const image=field('照片（压缩后保存在本机）','photo','','file');image.querySelector('input').accept='image/*';f.querySelector('.formgrid').append(image)}
function shrink(file){return new Promise((resolve,reject)=>{const im=new Image(),url=URL.createObjectURL(file);im.onload=()=>{const scale=Math.min(1,700/Math.max(im.width,im.height));const canvas=document.createElement('canvas');canvas.width=Math.round(im.width*scale);canvas.height=Math.round(im.height*scale);canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.65))};im.onerror=()=>{URL.revokeObjectURL(url);reject(Error('图片读取失败'))};im.src=url})}
function detail(id){const x=insects.find(v=>v.id===id);if(!x)return;selected=id;const root=E('div','','stack'),profile=E('div','','profile');if(x.photo){const im=E('img');im.src=x.photo;profile.append(im)}const kv=E('div','','kv');[['编号',x.code],['品种',x.species],['性别',x.sex],['阶段',x.stage],['体长',x.length?x.length+' mm':'—'],['体重',x.weight?x.weight+' g':'—'],['孵化',x.hatchDate],['羽化',x.emergeDate],['繁育状态',x.breeding],['备注',x.notes]].forEach(([k,v])=>kv.append(row(k,v)));profile.append(kv);root.append(profile);const lineage=box('🧬 血统关系');const parents=E('div','','actions');[['父虫',x.father],['母虫',x.mother]].forEach(([k,code])=>{const parent=insects.find(v=>v.code===code);parents.append(parent?b(k+' '+code+' ↗',()=>detail(parent.id)):E('span',k+': '+(code||'未填写')+(code?'（尚未录入）':''),'pill'))});lineage.append(parents);const children=insects.filter(v=>v.father===x.code||v.mother===x.code);if(children.length){lineage.append(E('p','子代：'));const links=E('div','','actions');children.forEach(ch=>links.append(b(ch.code,()=>detail(ch.id))));lineage.append(links)}root.append(lineage);const ev=box('成长 / 繁育时间线');const evact=E('div','','actions');evact.append(b('＋ 添加事件',()=>eventEditor(x.id)));ev.append(evact);[...x.events].sort((a,b)=>b.date.localeCompare(a.date)).forEach(e=>{const item=E('div','','event');item.append(E('strong',e.type+' · '+e.date),E('p',e.note));item.append(b(t('delete'),()=>{if(confirm('删除这条事件？')){x.events=x.events.filter(z=>z.id!==e.id);if(persist())detail(id)}},'danger small'));ev.append(item)});root.append(ev);const actions=E('div','','actions');actions.append(b(t('certificate'),()=>certificate(x.id)),b(t('edit'),()=>insectEditor(x.id)),b(t('delete'),()=>{if(confirm('确定删除该个体？其子代的父母编号将保留，但不再可点击。')){insects=insects.filter(z=>z.id!==id);if(persist()){close();render()}}},'danger small'));root.append(actions);open('🪲 '+x.code,root)}
function eventEditor(id){formDialog('新增成长 / 繁育事件',[['类型','type','观察','text',['观察','称重','蜕皮','化蛹','羽化','配对','产卵','孵化','其他']],['日期','date',new Date().toLocaleDateString('sv-SE'),'date'],['记录内容','note','','textarea']],v=>{if(!v.note.trim())return alert('请填写内容');const x=insects.find(x=>x.id===id);x.events.push({...v,id:uid()});if(persist())detail(id)})}
function breedingPage(c){title(t('breeding'),'记录配对、产卵、孵化与批次进度');const tb=E('div','','toolbar');tb.append(E('h2','繁育批次'),b('＋ 新增批次',()=>breedingEditor()));c.append(tb);if(!extra.breedings.length)c.append(E('div',t('empty'),'empty'));else c.append(makeTable(['批次','父虫','母虫','日期','产卵数','孵化数','操作'],extra.breedings.map(x=>[x.code,x.father,x.mother,x.date,x.eggs,x.hatched,[b(t('edit'),()=>breedingEditor(x.id)),b(t('delete'),()=>removeExtra('breedings',x.id),'danger small')]])))}
function breedingEditor(id){const x=extra.breedings.find(z=>z.id===id)||{code:'',father:'',mother:'',date:'',eggs:'',hatched:'',notes:''};formDialog(id?'编辑繁育批次':'新增繁育批次',[['批次编号','code',x.code],['父虫编号','father',x.father],['母虫编号','mother',x.mother],['配对日期','date',x.date,'date'],['产卵数','eggs',x.eggs,'number'],['孵化数','hatched',x.hatched,'number'],['备注','notes',x.notes,'textarea']],v=>{if(!v.code.trim())return alert('请输入批次编号');if(id)Object.assign(x,v);else extra.breedings.push({...v,id:uid()});if(persist()){close();render()}})}
function pedigreePage(c){title(t('pedigree'),'关联父母与子代；查看养殖者自行记录的血统证书');const tb=E('div','','toolbar');tb.append(E('h2','血统档案'),b('＋ 添加昆虫',()=>insectEditor()));c.append(tb);if(!insects.length){c.append(E('div','先录入昆虫档案，才能建立血统关系。','empty'));return}const grid=E('div','','grid');insects.forEach(x=>{const card=box('🧬 '+x.code);card.append(E('p',(x.species||'未填写品种')+' · '+x.sex+' · '+x.stage));card.append(E('p','父：'+(x.father||'未知')+' / 母：'+(x.mother||'未知'),'muted'));const children=insects.filter(z=>z.father===x.code||z.mother===x.code);card.append(E('p','已录入子代：'+children.length));card.append(b('查看关系',()=>detail(x.id)),b('生成证书',()=>certificate(x.id)));grid.append(card)});c.append(grid)}
function certificate(id){const x=insects.find(z=>z.id===id);if(!x)return;const root=E('div');const cert=E('div','','cert');cert.append(E('p','KABUTO-LUB / BREEDER RECORD'),E('h2','电子血统记录证书'),E('p','PEDIGREE RECORD · 飼育記録'));if(x.photo){const im=E('img');im.src=x.photo;cert.append(im)}cert.append(E('p',x.code,'big'),E('p',x.species||'—'));const kv=E('div','','kv');[['性别 / Sex',x.sex],['阶段 / Stage',x.stage],['父虫 / Sire',x.father],['母虫 / Dam',x.mother],['孵化 / Hatch',x.hatchDate],['羽化 / Emergence',x.emergeDate]].forEach(([k,v])=>kv.append(row(k,v)));cert.append(kv,E('p','本证书依据养殖者自行录入的信息生成，未经独立核验。\nSelf-reported breeding record. Not independently verified.','muted'));root.append(cert);const a=E('div','','actions no-print');a.append(b('打印 / 保存 PDF',()=>window.print()));root.append(a);open('血统记录 · '+x.code,root)}
function salesPage(c){title(t('sales'),'记录出售、成本和收益；不连接外部交易平台');const revenue=extra.sales.reduce((n,x)=>n+(Number(x.price)||0),0),cost=extra.sales.reduce((n,x)=>n+(Number(x.cost)||0),0);const stats=E('div','','stats');[['记录数',extra.sales.length],['销售额',revenue.toFixed(2)],['成本',cost.toFixed(2)],['毛利润',(revenue-cost).toFixed(2)]].forEach(([k,v])=>{const d=E('div','','stat');d.append(E('small',k),E('b',v));stats.append(d)});c.append(stats);const tb=E('div','','toolbar');tb.append(E('h2','销售记录'),b('＋ 新增记录',()=>saleEditor()));c.append(tb);c.append(E('p','金额为记录时使用的币种，不同币种请勿直接相加；当前统计不含汇率换算。','muted'));if(!extra.sales.length)c.append(E('div',t('empty'),'empty'));else c.append(makeTable(['日期','昆虫编号','币种','收入','成本','状态','操作'],extra.sales.map(x=>[x.date,x.code,x.currency,x.price,x.cost,x.status,[b(t('edit'),()=>saleEditor(x.id)),b(t('delete'),()=>removeExtra('sales',x.id),'danger small')]])))}
function saleEditor(id){const x=extra.sales.find(z=>z.id===id)||{date:'',code:'',currency:'CNY',price:'',cost:'',status:'待售',notes:''};formDialog(id?'编辑销售':'新增销售记录',[['日期','date',x.date,'date'],['昆虫编号','code',x.code],['币种','currency',x.currency,'text',['CNY','JPY','USD','EUR']],['收入','price',x.price,'number'],['成本','cost',x.cost,'number'],['状态','status',x.status,'text',['待售','已售','已完成']],['备注','notes',x.notes,'textarea']],v=>{if(id)Object.assign(x,v);else extra.sales.push({...v,id:uid()});if(persist()){close();render()}})}
function removeExtra(type,id){if(confirm('确定删除这条记录？')){extra[type]=extra[type].filter(x=>x.id!==id);if(persist())render()}}
function toolsPage(c){title(t('tools'),'繁育情景估算与商品文案生成（离线工具）');const grid=E('div','','cols2');const sim=box('🎮 繁育情景模拟');sim.append(E('p','仅做数学情景估算，不代表真实繁育成功率。','muted'));const f=E('form');f.append(field('预计产卵数','eggs','30','number'),field('假设孵化率 (%)','rate','70','number'),field('假设成虫存活率 (%)','survive','60','number'));const submit=E('button','计算情景');submit.type='submit';f.append(submit);const result=E('p','','kpi');f.append(result);f.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f)),eggs=Number(v.eggs),r=Number(v.rate),s=Number(v.survive);if(![eggs,r,s].every(Number.isFinite)||eggs<0||r<0||r>100||s<0||s>100)return alert('请输入有效参数');result.textContent=`预计孵化 ${Math.round(eggs*r/100)} 只 · 成虫 ${Math.round(eggs*r*s/10000)} 只`};sim.append(f);const gen=box('🛒 多语言商品文案');gen.append(E('p','根据档案生成可复制的模板；不是联网 AI。','muted'));const sel=field('选择昆虫','insect','', 'text',insects.map(x=>x.code));const out=field('文案','output','','textarea');out.querySelector('textarea').rows=9;gen.append(sel,b('生成中 / 日 / 英文案',()=>{const x=insects.find(v=>v.code===sel.querySelector('select').value);if(!x)return alert('请先创建昆虫档案');out.querySelector('textarea').value=`【中文】\n${x.species}｜编号 ${x.code}\n性别：${x.sex}；阶段：${x.stage}；体长：${x.length||'待测'} mm。\n血统信息由卖家自行记录，请联系确认。\n\n【日本語】\n${x.species}｜個体番号 ${x.code}\n性別：${x.sex}、ステージ：${x.stage}、体長：${x.length||'未測定'} mm。血統情報は飼育者の自己申告です。\n\n【English】\n${x.species} | ID ${x.code}\nSex: ${x.sex}; stage: ${x.stage}; length: ${x.length||'N/A'} mm. Lineage is breeder-reported and unverified.`}));gen.append(out);grid.append(sim,gen);c.append(grid);c.append(E('div','真实 AI 助手需要安全的服务端接口和密钥管理；当前版本不包含联网 AI。','notice'))}
function exportData(){const payload={app:'Kabuto-Lub',version:'1.0',exportedAt:new Date().toISOString(),insects,breedings:extra.breedings,sales:extra.sales};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=E('a');a.href=url;a.download='kabuto-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function settingsPage(c){title(t('settings'),'备份、恢复、语言及商业版建设状态');const card=box('💾 数据备份');card.append(E('p','导出包含昆虫档案、照片、成长事件、繁育批次及销售记录的 JSON 文件。'));const actions=E('div','','actions');actions.append(b('⬇ 导出 JSON',exportData),b('⬆ 导入 JSON',()=>$('importFile').click()));card.append(actions);c.append(card);const state=box('☁️ 商业化接入状态');[['本地档案、血统、繁育与销售','已实现'],['中文 / 日文 / 英文导航','已实现（部分业务表单仍为中文）'],['用户登录及云端同步','尚未接入'],['真实 AI 分析','尚未接入'],['付费订阅与支付','尚未接入'],['公开可验证证书二维码','尚未接入']].forEach(([k,v])=>state.append(row(k,v)));c.append(state);c.append(E('div','隐私提示：照片和数据保存在当前浏览器 localStorage。清除网站数据、更换浏览器或设备可能导致丢失，请定期导出备份。','notice'))}
$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());let arr,breeds=[],sales=[];if(Array.isArray(data))arr=data;else if(Array.isArray(data.insects)){arr=data.insects;breeds=Array.isArray(data.breedings)?data.breedings:[];sales=Array.isArray(data.sales)?data.sales:[]}else if(Array.isArray(data.data))arr=data.data;else throw Error('无法识别文件格式');if(arr.length>10000)throw Error('记录数量超限');const normalized=arr.map(norm);if(!confirm(`将用备份中的 ${normalized.length} 条昆虫档案替换当前全部数据（包括繁育和销售记录）。确定继续？`))return;const oldInsects=insects,oldExtra=extra;insects=normalized;extra={breedings:breeds,sales};if(!persist()){insects=oldInsects;extra=oldExtra;return}render();alert('导入完成')}catch(err){alert('导入失败：'+err.message)}finally{e.target.value=''}};
$('exportTop').onclick=exportData;$('closeModal').onclick=close;$('modal').onclick=e=>{if(e.target===$('modal'))close()};$('lang').onchange=e=>{lang=e.target.value;localStorage.setItem(LANG,lang);render()};load();render();
