// Kabuto-Lub V1.1 — optional, user-controlled cloud synchronization.
// The existing app.js continues to own all local data and UI.
const DEFAULT_URL='https://ljmczkhxljrmpgwwqrct.supabase.co';
const PUBLIC_KEY='sb_publishable_aXnPc5jdazRYk19yNaGdKg_oaNfnSva';
const LS_INSECTS='kabuto_insects', LS_EXTRA='kabuto_v1_business';
const $=id=>document.getElementById(id);
let sb=null,session=null,busy=false;
const mask=document.createElement('div');mask.className='cloud-mask';mask.hidden=true;
mask.innerHTML=`<div class="cloud-panel" role="dialog" aria-modal="true" aria-label="Kabuto 云端账户"><div class="cloud-row"><h2>☁️ Kabuto 云端</h2><button type="button" id="cloudClose" class="secondary">关闭</button></div><p>本地档案仍保存在本机。云端操作由你手动确认，不会自动覆盖数据。</p><div id="cloudSignedOut"><label>邮箱</label><input id="cloudEmail" type="email" autocomplete="email" placeholder="you@example.com"><label>密码（至少 6 位）</label><input id="cloudPassword" type="password" autocomplete="current-password" minlength="6"><button id="cloudLogin">登录</button><button id="cloudSignup" class="secondary">注册</button><p class="cloud-small">注册后如开启邮箱验证，请先打开邮件中的确认链接，再返回这里登录。</p></div><div id="cloudSignedIn" hidden><p>当前账户：<strong id="cloudAccount"></strong></p><div class="cloud-warning">⚠️ 首次同步前，请先点击原页面的「导出备份」保存 JSON。上传会按记录 ID 写入云端；下载会合并云端记录到本机，遇到同 ID 的记录以云端为准。</div><p id="cloudCounts"></p><button id="cloudUpload">⬆️ 上传本机数据</button><button id="cloudDownload" class="secondary">⬇️ 下载云端数据</button><button id="cloudLogout" class="secondary">退出登录</button><p class="cloud-small">当前版本照片仅保留在本机，暂不上传图片。父母编号、成长记录、繁育与销售文字信息可同步。</p></div><hr><details><summary>高级设置：Supabase 项目地址</summary><p class="cloud-small">如果连接失败，请从 Supabase 项目主页复制 Project URL 并粘贴在这里。只填写项目 URL，不填写数据库密码或 Secret Key。</p><input id="cloudUrl" type="url"><button id="cloudSaveUrl" class="secondary">保存地址</button></details><div id="cloudMessage" class="cloud-msg" role="status"></div></div>`;
document.body.append(mask);
const msg=s=>{$('cloudMessage').textContent=s};
const getUrl=()=>localStorage.getItem('kabuto_supabase_url')||DEFAULT_URL;
$('cloudUrl').value=getUrl();
$('cloudOpen').onclick=()=>{mask.hidden=false;counts();};
$('cloudClose').onclick=()=>mask.hidden=true;
mask.addEventListener('click',e=>{if(e.target===mask)mask.hidden=true});
$('cloudSaveUrl').onclick=()=>{try{const u=new URL($('cloudUrl').value.trim());if(u.protocol!=='https:'||!u.hostname.endsWith('.supabase.co'))throw Error('请输入有效的 https://*.supabase.co 地址');localStorage.setItem('kabuto_supabase_url',u.origin);msg('地址已保存，请刷新页面重新连接。')}catch(e){msg(e.message)}};
function localData(){let ins=[],ext={};try{ins=JSON.parse(localStorage.getItem(LS_INSECTS)||'[]');ext=JSON.parse(localStorage.getItem(LS_EXTRA)||'{}')}catch(e){throw Error('本机数据无法解析：'+e.message)}if(!Array.isArray(ins))throw Error('本机昆虫数据格式错误');return {ins,breedings:Array.isArray(ext.breedings)?ext.breedings:[],sales:Array.isArray(ext.sales)?ext.sales:[]}}
function counts(){try{const x=localData();$('cloudCounts').textContent=`本机：${x.ins.length} 只昆虫、${x.ins.reduce((n,i)=>n+(i.events||[]).length,0)} 条成长记录、${x.breedings.length} 个繁育批次、${x.sales.length} 条销售记录。`}catch(e){msg(e.message)}}
function view(){const logged=!!session?.user;$('cloudSignedOut').hidden=logged;$('cloudSignedIn').hidden=!logged;$('cloudAccount').textContent=session?.user?.email||'';$('cloudOpen').textContent=logged?'☁️ '+(session.user.email?.split('@')[0]||'已登录'):'☁️ 登录 / 云同步';counts()}
async function init(){try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');sb=createClient(getUrl(),PUBLIC_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await sb.auth.getSession();if(error)throw error;session=data.session;sb.auth.onAuthStateChange((_event,s)=>{session=s;view()});view()}catch(e){msg('云端初始化失败：'+e.message+'。请检查项目 URL、网络和 Supabase 服务状态。')}}
async function task(fn){if(busy)return;busy=true;for(const id of ['cloudUpload','cloudDownload','cloudLogin','cloudSignup'])$(id).disabled=true;try{if(!sb)throw Error('云端客户端尚未连接');await fn()}catch(e){msg('操作失败：'+(e.message||e))}finally{busy=false;for(const id of ['cloudUpload','cloudDownload','cloudLogin','cloudSignup'])$(id).disabled=false;view()}}
$('cloudSignup').onclick=()=>task(async()=>{const email=$('cloudEmail').value.trim(),password=$('cloudPassword').value;if(!email||password.length<6)throw Error('请输入邮箱及至少 6 位密码');const {data,error}=await sb.auth.signUp({email,password,emailRedirectTo:location.origin+location.pathname});if(error)throw error;msg(data.session?'注册并登录成功。':'注册请求已提交。如启用邮件验证，请查收邮件并确认后登录。')});
$('cloudLogin').onclick=()=>task(async()=>{const {error}=await sb.auth.signInWithPassword({email:$('cloudEmail').value.trim(),password:$('cloudPassword').value});if(error)throw error;msg('登录成功。请先备份，再选择上传或下载。')});
$('cloudLogout').onclick=()=>task(async()=>{const {error}=await sb.auth.signOut();if(error)throw error;msg('已退出云端账户；本机数据未删除。')});
const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
const num=x=>x===''||x===null||x===undefined?null:Number.isFinite(Number(x))?Number(x):null;
const date=x=>/^\d{4}-\d{2}-\d{2}$/.test(x||'')?x:null;
const ensureId=(x,map,key)=>{if(uuid(x.id))return x.id;const k=key+':'+String(x.id||x.code||'');if(!map[k])map[k]=crypto.randomUUID();return map[k]};
const mappings=()=>{try{return JSON.parse(localStorage.getItem('kabuto_cloud_ids')||'{}')}catch{return {}}};
const saveMap=m=>localStorage.setItem('kabuto_cloud_ids',JSON.stringify(m));
async function write(table,rows){if(!rows.length)return;for(let i=0;i<rows.length;i+=100){const {error}=await sb.from(table).upsert(rows.slice(i,i+100),{onConflict:'id'});if(error)throw Error(table+': '+error.message)}}
async function read(table){const out=[];for(let start=0;;start+=500){const {data,error}=await sb.from(table).select('*').range(start,start+499).order('created_at',{ascending:true});if(error)throw Error(table+': '+error.message);out.push(...data);if(data.length<500)break}return out}
$('cloudUpload').onclick=()=>task(async()=>{if(!session?.user)throw Error('请先登录');if(!confirm('确认已导出 JSON 备份？即将把本机记录上传到当前账号云端；同 ID 记录将更新。照片不会上传。'))return;const {ins,breedings,sales}=localData(),uid=session.user.id,map=mappings();const ids=new Map();for(const x of ins)ids.set(String(x.id),ensureId(x,map,'insect'));const insects=ins.map(x=>({id:ids.get(String(x.id)),user_id:uid,code:String(x.code||''),species:x.species||'',sex:x.sex||'',stage:x.stage||'',length_mm:num(x.length),weight_g:num(x.weight),hatch_date:date(x.hatchDate),emerge_date:date(x.emergeDate),father_code:x.father||'',mother_code:x.mother||'',breeding_status:x.breeding||'',notes:x.notes||'',photo_path:null,legacy_id:uuid(x.id)?null:String(x.id||'')}));const events=ins.flatMap(x=>(x.events||[]).map(e=>({id:ensureId(e,map,'event'),user_id:uid,insect_id:ids.get(String(x.id)),event_type:e.type||'',event_date:date(e.date),note:e.note||''})));const batches=breedings.map(x=>({id:ensureId(x,map,'batch'),user_id:uid,batch_code:x.code||x.batchCode||'',father_id:ids.get(String(x.fatherId||''))||null,mother_id:ids.get(String(x.motherId||''))||null,pairing_date:date(x.date||x.pairingDate),egg_count:num(x.eggs??x.eggCount),hatch_count:num(x.hatched??x.hatchCount),status:x.status||'',notes:x.notes||''}));const saleRows=sales.map(x=>({id:ensureId(x,map,'sale'),user_id:uid,insect_id:ids.get(String(x.insectId||''))||null,item_name:x.item||x.itemName||x.name||'',currency:x.currency||'CNY',sale_price:num(x.price??x.salePrice),cost:num(x.cost),sold_at:date(x.date||x.soldAt),status:x.status||'',notes:x.notes||''}));saveMap(map);await write('insects',insects);await write('growth_events',events);await write('breeding_batches',batches);await write('sales',saleRows);msg(`上传完成：昆虫 ${insects.length}、成长记录 ${events.length}、繁育 ${batches.length}、销售 ${saleRows.length}。图片未上传。`)});
$('cloudDownload').onclick=()=>task(async()=>{if(!session?.user)throw Error('请先登录');if(!confirm('下载会把云端记录合并进本机；同 ID 的本机记录将以云端字段为准。请先导出 JSON 备份。是否继续？'))return;const [ins,events,batches,sales]=await Promise.all(['insects','growth_events','breeding_batches','sales'].map(read));const current=localData();const byId=new Map(current.ins.map(x=>[String(x.id),x]));const eventByInsect=new Map();for(const e of events){if(!eventByInsect.has(e.insect_id))eventByInsect.set(e.insect_id,[]);eventByInsect.get(e.insect_id).push({id:e.id,type:e.event_type||'',date:e.event_date||'',note:e.note||''})}for(const x of ins){const old=byId.get(x.id)||current.ins.find(y=>y.code===x.code);const mapped={id:x.id,code:x.code||'',species:x.species||'',sex:x.sex||'未知',stage:x.stage||'未知',length:x.length_mm==null?'':String(x.length_mm),weight:x.weight_g==null?'':String(x.weight_g),hatchDate:x.hatch_date||'',emergeDate:x.emerge_date||'',father:x.father_code||'',mother:x.mother_code||'',breeding:x.breeding_status||'未配对',notes:x.notes||'',photo:old?.photo||'',events:eventByInsect.get(x.id)||[]};if(old)byId.delete(String(old.id));byId.set(x.id,mapped)}const ex={breedings:[...current.breedings],sales:[...current.sales]};for(const x of batches){const v={id:x.id,code:x.batch_code||'',fatherId:x.father_id||'',motherId:x.mother_id||'',date:x.pairing_date||'',eggs:x.egg_count??'',hatched:x.hatch_count??'',status:x.status||'',notes:x.notes||''};const i=ex.breedings.findIndex(z=>z.id===x.id);if(i<0)ex.breedings.push(v);else ex.breedings[i]=v}for(const x of sales){const v={id:x.id,insectId:x.insect_id||'',item:x.item_name||'',currency:x.currency||'CNY',price:x.sale_price??'',cost:x.cost??'',date:x.sold_at||'',status:x.status||'',notes:x.notes||''};const i=ex.sales.findIndex(z=>z.id===x.id);if(i<0)ex.sales.push(v);else ex.sales[i]=v}try{localStorage.setItem(LS_INSECTS,JSON.stringify([...byId.values()]));localStorage.setItem(LS_EXTRA,JSON.stringify(ex))}catch(e){throw Error('本机空间不足，未能完整保存下载结果：'+e.message)}msg(`下载完成：云端昆虫 ${ins.length}、成长记录 ${events.length}、繁育 ${batches.length}、销售 ${sales.length}。即将刷新页面。`);setTimeout(()=>location.reload(),1400)});
init();
